config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do
    resources :posts, except: [:index]
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
   

  get 'about' => 'welcome#about'
  
  root 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    # Because comments already depend on posts, they will also be deleted when a topic is deleted.
    validates :name, length: { minimum: 5 }, presence: true
    validates :description, length: { minimum: 15 }, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    
    # We use the before_action filter and the require_sign_in method from  ApplicationController to redirect guest users
    # who attempt to access controller actions other than index or show.
    before_action :require_sign_in, except: [:index, :show]
    # We use another before_action filter to check the role of signed-in users. If the  current_user isn't an admin,
    # we'll redirect them to the topics index view.
    
    before_action :authorize_moderator, only: [:edit, :update]
    before_action :authorize_admin, except: [:index, :edit, :update, :show]
    
    def index
        @topics = Topic.all
    end
    
    def show
        @topic = Topic.find(params[:id])
    end
    
    def new
        @topic = Topic.new
    end
    
    
    def create
        @topic = Topic.new(topic_params)
 
        if @topic.save
            redirect_to @topic, notice: "Topic was saved successfully."
        else
            flash.now[:alert] = "Error creating topic. Please try again."
            render :new
        end
    end
    
    def edit
        @topic = Topic.find(params[:id])
    end
    
    def update
        @topic = Topic.find(params[:id])
 
        @topic.assign_attributes(topic_params)
 
        if @topic.save
            flash[:notice] = "Topic was updated."
            redirect_to @topic
        else
            flash.now[:alert] = "Error saving topic. Please try again."
            render :edit
        end
    end
    
    def destroy
        @topic = Topic.find(params[:id])
 
        if @topic.destroy
            flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
            # Redirect_to action: :index is the same as redirect_to topics_path because
            # topics_path routes to the index action per Rails' resourceful routing.
            redirect_to action: :index
        else
            flash.now[:alert] = "There was an error deleting the topic."
            render :show
        end
    end
    
    private
 
    def topic_params
        params.require(:topic).permit(:name, :description, :public)
    end
    
    # We define authorize_user, which is used in line 8 to redirect non-admin users to  topics_path (the topics index view).
    def authorize_moderator
        unless (current_user.admin? || current_user.moderator?)
            flash[:alert] = "You must be an admin or moderator to do that."
            redirect_to topics_path
        end
    end
    
    def authorize_admin
        unless current_user.admin?
            flash[:alert] = "You must be an admin to do that."
            redirect_to topics_path
        end
    end
    
end

app/helpers/topics_helper.rb
module TopicsHelper
    def user_is_authorized_for_topics?
        current_user && current_user.admin?
    end
    def user_is_moderator_for_topics?
        current_user && current_user.moderator?
    end
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
    <% if topic.errors.any? %>
        <!-- If there are any validation errors, we display an alert with the number of errors and their messages. -->
        <div class="alert alert-danger">
            <!-- We use the pluralize method to pluralize "error" if there is more than one error. -->
            <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
            <ul>
                <% topic.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= form_group_tag(topic.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
    <% end %>
    <%= form_group_tag(topic.errors[:description]) do %>
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
    <% end %>
    <div class="form-group">
        <!--We pass a block to f.label to generate the HTML for a checkbox. -->
        <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public topic
        <% end %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/_post.html.erb
<% @topic.posts.each do |post| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">
                <!-- We refactor how we link to individual posts using the topic_post_path method.
                     # This helper takes a topic and a post and generates a path to the posts show view. -->
                <%= link_to post.title, topic_post_path(@topic, post) %>
            </h4>
            <!-- We add submission and comment details for each post in the show view. -->
            <small>
                submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
                <%= post.comments.count %> Comments
            </small>
        </div>
    </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="media">
    <div class="media-body">
        <h4 class="media-heading">
            <!-- We create a link to the show view for each topic. -->
            <%= link_to topic.name, topic %>
        </h4>
        <small>
            <%= topic.description %>
        </small>
    </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
 
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for topics:</p>
        <ul>
            <li>Make sure the topic is appropriate.</li>
            <li>Never insult dogs.</li>
            <li>Smile when you type.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>
 
<div class="row">
    <div class="col-md-8">
        <!-- We use partials to render each topic in @topics. -->
        <% @topics.each do |topic| %>
            <%= render partial: 'topic', locals: { topic: topic } %>
        <% end %>    
    </div>
    <div class="col-md-4">
        <!-- We create a link to create a new topic. -->
        <!-- We check if there is a signed-in current_user, and that current_user is an admin. -->
        <% if user_is_authorized_for_topics? %>
            <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
        <% end %>    
    </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
 
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for topics:</p>
        <ul>
            <li>Make sure the topic is appropriate.</li>
            <li>Never insult dogs.</li>
            <li>Smile when you type.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic } %>
    </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
 
<% if current_user %>
    <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
<% end %>
 
<div class="row">
    <div class="col-md-8">
        <p class="lead"><%= @topic.description %></p>
        <!-- We iterate over the posts belonging to @topic, and display each post. -->
        <% @topic.posts.each do |post| %>
            <div class="media">
                <%= render partial: 'votes/voter', locals: { post: post } %>
                <div class="media-body">
                    <h4 class="media-heading">
                        <!-- We refactor how we link to individual posts using the topic_post_path method.
                        # This helper takes a topic and a post and generates a path to the posts show view. -->
                        <%= link_to post.title, topic_post_path(@topic, post) %>
                    </h4>
                    <!-- We add submission and comment details for each post in the show view. -->
                    <small>
                        submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
                        <%= post.comments.count %> Comments
                    </small>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-4">
        <!-- We replace new_post_path with new_topic_post_path to reflect the nested route we generated in routes.rb. -->
        <% if user_is_authorized_for_topics? %>
            <%= link_to "Edit Topic", edit_topic_path(@topic), class: 'btn btn-success' %>
            <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
        <% end %>
    </div>
</div>