config/routes.rb
Rails.application.routes.draw do
  
  resources :topics do
    resources :posts, except: [:index]
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
   

  get 'about' => 'welcome#about'
  
  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    # We add the votes association to Post. This relates the models and allows us to call post.votes. We also add 
    # dependent: :destroy to ensure that votes are destroyed when their parent post is deleted.
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    # The default_scope will order all posts by their rank inn descending order.
    default_scope { order('rank DESC') }
    # We use a lambda (->) to ensure that a user is present or signed in. If the user is present, we return all posts. 
    # If not, we use the Active Record joins method to retrieve all posts which belong to a public topic.
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
    
    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :topic, presence: true
    validates :user, presence: true
    
    
    def up_votes
        # We find the up votes for a post by passing value: 1 to where. This fetches a collection of votes with a value of 1.
        # We then call count on the collection to get a total of all up votes.
        votes.where(value: 1).count
    end
 
    def down_votes
        # We find the down votes for a post by passing value: -1 to where.  where(value: -1) fetches only the votes with a value of -1.
        # We then call count on the collection to get a total of all up votes.
        votes.where(value: -1).count
    end
 
    def points
        # We use ActiveRecord's sum method to add the value of all the given post's votes. Passing :value to 
        # sum tells it what attribute to sum in the collection.
        votes.sum(:value)
    end
    
    def update_rank
        age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
        new_rank = points + age_in_days
        update_attribute(:rank, new_rank)
    end
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # There's no longer an index route for posts. This is because the posts index view is no longer needed. 
  # All posts will be displayed with respect to a topic now, on the topics show view. Remove the index action from the PostsController
  
  # We use a before_action filter to call the require_sign_in method before each of our controller actions, except for the show action.
  before_action :require_sign_in, except: :show
  # We use a second before_action filter to check the role of a signed-in user. If the current_user isn't authorized based on their role, 
  # we'll redirect them to the posts show view.
  before_action :authorize_user, except: [:show, :new, :create]
  

  def show
    # We find the post that corresponds to the id in the params that was passed to  show and assign
    # it to @post. Unlike in the index method, in the show method, we populate an instance variable
    # with a single post, rather than a collection of posts.
    @post = Post.find(params[:id])
  end

  def new
    # We create an instance variable, @post, then assign it an empty post returned by  Post.new.
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end
  
  def create
    
    @topic = Topic.find(params[:topic_id])
    # We assign a topic to a post.
    @post = @topic.posts.build(post_params)
    # We assign @post.user in the same way we assigned @post.topic, to properly scope the new post.
    @post.user = current_user

    # If we successfully save Post to the database, we display a success message using flash[:notice] and redirect
    # the user to the route generated by @post. Redirecting to @post will direct the user to the posts show view.
    if @post.save
      # We assign a value to flash[:notice]. The flash hash provides a way to pass temporary values between actions.
      # Any value placed in flash will be available in the next action and then deleted.
      flash[:notice] = "Post was saved."
      # We change the redirect to use the nested post path.
      redirect_to [@topic, @post]
    else
      # If we do not successfully save Post to the database, we display an error message and render the new view again.
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
 
    if @post.save
      flash[:notice] = "Post was updated."
      # We change the redirect to use the nested post path.
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
 
    # We call destroy on @post. If that call is successful, we set a flash message and redirect
    # the user to the posts index view. If destroy fails then we redirect the user to the show view using render :show.
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      # When a post is deleted, we direct users to the topic show view.
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end
  
  # remember to add private methods to the bottom of the file. Any method defined below private, will be private.
  private
 
  def post_params
    params.require(:post).permit(:title, :body)
  end
  
  def authorize_user
    post = Post.find(params[:id])
    # We redirect the user unless they own the post they're attempting to modify, or they're an admin.
    unless current_user == post.user || current_user.admin? || current_user.moderator?
      flash[:alert] = "You must be an admin to do that."
      redirect_to [post.topic, post]
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
    def user_is_authorized_for_post?(post)
        current_user && (current_user == post.user || current_user.admin?)
    end
    def user_is_moderator_for_post?
        current_user && current_user.moderator?
    end
end

app/views/posts/_form.html.erb
<!-- We use the topic and post local variables we passed into the partial when we rendered it. Our view is called
     _form.html.erb, while we render the partial: 'form'. This is a Rails convention for partial naming. If we don't 
     follow it, the partial will not be found. -->
<%= form_for [topic, post] do |f| %>
    <% if post.errors.any? %>
        <!-- If there are any validation errors, we display an alert with the number of errors and their messages. -->
        <div class="alert alert-danger">
            <!-- We use the pluralize method to pluralize "error" if there is more than one error. -->
            <h4><%= pluralize(post.errors.count, "error") %>.</h4>
            <ul>
                <% post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <!-- We use form_group_tag to display title errors. -->
    <%= form_group_tag(post.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
    <% end %>
    <!-- We use form_group_tag to display body errors. -->
    <%= form_group_tag(post.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    <% end %>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
    <%= render partial: 'votes/voter', locals: { post: post } %>
    <div class="media-body">
        <h4 class="media-heading">
            <%= link_to post.title, topic_post_path(post.topic, post) %>
            <%= image_tag(post.user.avatar_url(48), class: "gravatar") %>
        </h4>
        <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
            <%= post.comments.count %> Comments
        </small>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <!-- Partials are fragments of view code, which are called from views. Partials are called with the 
             render method. Rendering a partial is like copying and pasting view code from another file.
             Our view is called _form.html.erb, while we render the partial: 'form'. This is a Rails convention
             for partial naming. If we don't follow it, the partial will not be found. -->
        <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
 
<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-md-8">
        <div>
            <!-- It's a good idea to pass post in explicitly, rather than implicitly expect @post. This is why the partial
                 we created references post instead of @post. -->
            <%= render partial: 'votes/voter', locals: { post: @post } %>
            <h1>
                <%= @post.title %> <br>
                <small>
                    submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
                </small>
            </h1>
        </div>
        <div>
            <h3>Comments</h3>
            <!-- We will call _comment.html.erb and render all the comments which belong to the given post. -->
            <%= render @post.comments %>
        </div>
        <!-- We allow signed in users to see the comment form. -->
        <% if current_user %>
            <!-- We render the comment form, and use comments/form, because we are rendering the comment form from a
                 post view. If we didn't specify comments, Rails would render the posts form partial by default. -->
            <%= render 'comments/form', comment: Comment.new, post: @post %>
        <% end %>
    </div>
    <div class="col-md-4">
        <!-- We format a link as an Edit button which directs a user to  /posts/@post.id/edit.  
             edit_post_path(@post) is a helper method that is generated in  routes.rb by resources :posts.  -->
        <% if user_is_authorized_for_post?(@post) %>     
            <!-- We replace edit_post_path with edit_topic_post_path, which takes two arguments, a topic and a post. -->
            <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
        
            <!-- We use link_to to create a delete button. The text on the button is Delete Post. We override
                 the default method (:post) with :delete so that when the button is pressed the route called is the delete 
                 route. We style the button by setting class: to 'btn btn-danger'. We pass a Hash with the confirm: key to 
                 the data: argument. This confirms the action with a JavaScript confirmation dialog when a user presses the button. -->
             
            <!-- We update link_to to take an array consisting of a topic and post, which it uses to build the link to delete a nested post. -->
            <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
        <% end %>
    </div>
    <div class="col-md-4">
        <h3>
            <!-- We use the pluralize helper method to display the correctly pluralized forms of "point", "up vote", and "down vote". -->
            <%= pluralize(@post.points, 'point') %>
            <div>
                <small>
                    <%= pluralize(@post.up_votes, 'up vote') %>,
                    <%= pluralize(@post.down_votes, 'down vote') %>
                </small>
            </div>
        </h3>
        <% if current_user %>
            <%= render partial: 'favorites/favorite', locals: { post: @post } %>
        <% end %>
    </div>
</div>